[package]
name = "audio-codec"
version = "0.4.0"
edition = "2024"
authors = ["jinti<shenjindi@fourz.cn>"]
description = "A collection of VoIP audio codecs in pure Rust, including G.711, G.722, G.729, and Opus."
license = "MIT"
repository = "https://github.com/restsend/audio-codec"
readme = "README.md"
keywords = ["sip", "voip", "telephony", "webrtc", "no_std"]
categories = ["multimedia", "no-std"]

[features]
default = ["std"]
std = ["dep:anyhow", "g729-sys/std"]
opus = ["dep:opus-rs", "std"]

[lib]
crate-type = ["rlib"]

[dependencies]
anyhow = { version = "1", optional = true }
g729-sys = { version = "0.2", default-features = false }
opus-rs = { version = "0.1.26", optional = true }
libm = { version = "0.2", default-features = false }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
opusic-sys = "0.7.3"


[[bench]]
name = "codec_bench"
harness = false
